
INSERT INTO pregunta (padre_id, nombre, emoji, texto, visitas, is_final) VALUES
  (null,	"Inicio",	"😎",	"texto inicio",	0,	FALSE),
  (1,	"Nosotros",	"😎",	"texto nosotros",	0,	FALSE),
  (1,	"Lineas de negocio",	"🛒",	"texto lineas de negocio",	0,	FALSE),
  (1,	"Proyectos y Reconocimientos",	"😎",	"texto proyectos y reconocimientos",	0,	FALSE),
  (1,	"Aplicaciones",	"👨‍🔧",	"texto aplicaciones",	0,	FALSE),
  (1,	"Oportunidades",	"🤩",	"texto oportunidades",	0,	FALSE),
  (1,	"Contacto",	"📞",	"mostrarFormulario()",	0,	TRUE),
  (2,	"¿Quienes somos?",	"❓",	"texto quienes somos",	0,	FALSE),
  (2,	"Misión",	"🎯",	"texto mision",	0,	TRUE),
  (2,	"Visión",	"👀",	"texto vision",	0,	TRUE),
  (2,	"Valores",	"❤"	,"texto valores",	0,	TRUE),
  (2,	"Colaboradores",	"🤝",	"texto colaboradores",	0,	FALSE),
  (8,	"Nombre de la empresa",	"🏭",	"texto nombre empresa",	0,	TRUE),
  (8,	"¿Qué significa Naatik?",	"🤔",	"texto que significa",	0,	TRUE),
  (8,	"Historia",	"🧐",	"texto historia",	0,	TRUE),
  (8,	"Claves de registro nacionales",	"📝",	"texto claves",	0,	TRUE),
  (12,	"Socios principales",	"📝",	"texto socios principales",	0,	TRUE),
  (12,	"Instituciones",	"📝",	"texto instituciones",	0,	TRUE),
  (12,	"Empresas hermanas",	"📝",	"texto empresas hermanas",	0,	TRUE),
  (3,	"Desarrollo de sistemas informáticos",	"📝",	"Linea de negocio 1",	0,	TRUE),
  (3,	"Vinculación Academia-Industria",	"📝",	"Linea de negocio 2",	0,	TRUE),
  (3,	"Atención a convocatorias para desarrollo de proyectos",	"📝",	"Linea de negocio 3",	0,	TRUE),
  (6,	"Estancias para tesis o servicio social",	"📝",	"texto estancias",	0,	FALSE),
  (6,	"¿Cómo podemos contactarlos?",	"📝",	"texto como contactar",	0,	TRUE),
  (23,	"Requisitos",	"📝",	"texto requisitos",	0,	TRUE),
  (23,	"Beneficios",	"📝",	"texto beneficios",	0,	TRUE),
  (23,	"Documentacion requerida",	"📝",	"texto documentacion",	0,	TRUE),
  (23,	"Actividades a realizar",	"📝",	"texto actividades",	0,	TRUE),
  (23,	"Cómo aplicar",	"📝",	"texto como aplicar",	0,	TRUE);

  
